-- MySQL Script generated by MySQL Workbench
-- 09/02/15 20:52:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`decisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`decisions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`decisions` (
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `protocolNumber` VARCHAR(45) NULL COMMENT '',
  `subject` VARCHAR(45) NULL COMMENT '',
  `issueDate` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL COMMENT '',
  `decisionTypeId` VARCHAR(45) NULL COMMENT '',
  `organizationId` VARCHAR(45) NULL COMMENT '',
  `privateData` VARCHAR(45) NULL COMMENT '',
  `submissionTimestamp` VARCHAR(45) NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `versionId` VARCHAR(45) NULL COMMENT '',
  `documentChecksum` VARCHAR(45) NULL COMMENT '',
  `correctedVersionId` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ada`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unitsperdecisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`unitsperdecisions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`unitsperdecisions` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ada` VARCHAR(45) NULL COMMENT '',
  `unitID` INT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `ADA_FK_idx` (`ada` ASC)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`signersperdecisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`signersperdecisions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`signersperdecisions` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ada` VARCHAR(45) NULL COMMENT '',
  `signerID` INT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `ADA_FK_idx` (`ada` ASC)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amountWithKae`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`amountWithKae` ;

CREATE TABLE IF NOT EXISTS `mydb`.`amountWithKae` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ada` VARCHAR(20) NULL COMMENT '',
  `afm` VARCHAR(30) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `kae` VARCHAR(45) NOT NULL COMMENT '',
  `amount` FLOAT NOT NULL COMMENT '',
  `kaeCreditRemainder` FLOAT NULL COMMENT '',
  `kaeBudgetRemainder` FLOAT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `ADA_FK_idx` (`ada` ASC)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`decisionsB13`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`decisionsB13` ;

CREATE TABLE IF NOT EXISTS `mydb`.`decisionsB13` (
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `financialYear` TINYINT NOT NULL COMMENT '',
  `budgettype` VARCHAR(45) NOT NULL COMMENT '',
  `entryNumber` VARCHAR(20) NULL COMMENT '',
  `partialead` TINYINT(1) NOT NULL COMMENT '',
  `recalledExpenseDecision` TINYINT(1) NULL COMMENT '',
  `amount` FLOAT NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `relatedPartialADA` VARCHAR(20) NULL COMMENT '',
  `documentType` VARCHAR(20) NULL COMMENT '',
  `amountWithKae_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ada`)  COMMENT '',
  INDEX `fk_decisionsB13_amountWithKae1_idx` (`amountWithKae_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_decisionsB13_amountWithKae1`
    FOREIGN KEY (`amountWithKae_ID`)
    REFERENCES `mydb`.`amountWithKae` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`decisionsB21`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`decisionsB21` ;

CREATE TABLE IF NOT EXISTS `mydb`.`decisionsB21` (
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(45) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `decisionsB21col` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `documentType` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`ada`)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`decisionsB22`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`decisionsB22` ;

CREATE TABLE IF NOT EXISTS `mydb`.`decisionsB22` (
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(45) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `documentType` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`ada`)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sponsor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sponsor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sponsor` (
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(45) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `amount` VARCHAR(45) NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `cpv` VARCHAR(15) NULL COMMENT '',
  `kae` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ada`)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`decisionsD1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`decisionsD1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`decisionsD1` (
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(45) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `amount` VARCHAR(45) NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `assignmentType` VARCHAR(45) NULL COMMENT '',
  `textRelatedADA` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`ada`)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cpvperdecisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cpvperdecisions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cpvperdecisions` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `cpv` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `ADA_FK_idx` (`ada` ASC)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`decisionsD21`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`decisionsD21` ;

CREATE TABLE IF NOT EXISTS `mydb`.`decisionsD21` (
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `contestProgressType` VARCHAR(45) NULL COMMENT '',
  `manifestSelectionCriterion` VARCHAR(45) NULL COMMENT '',
  `manifestContractType` VARCHAR(45) NULL COMMENT '',
  `orgBudgetCode` VARCHAR(45) NULL COMMENT '',
  `amount` FLOAT NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `textRelatedADA` VARCHAR(45) NULL COMMENT '',
  `documentType` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ada`)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`decisionsD22`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`decisionsD22` ;

CREATE TABLE IF NOT EXISTS `mydb`.`decisionsD22` (
  `ada` VARCHAR(15) NOT NULL COMMENT '',
  `afm` VARCHAR(20) NULL COMMENT '',
  `afmType` VARCHAR(45) NULL COMMENT '',
  `afmCountry` VARCHAR(45) NULL COMMENT '',
  `enterName` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `noVATOrg` VARCHAR(45) NULL COMMENT '',
  `amount` FLOAT NULL COMMENT '',
  `currency` VARCHAR(45) NULL COMMENT '',
  `textRelatedADA` VARCHAR(100) NULL COMMENT '',
  `relatedDecisionsADA` VARCHAR(15) NULL COMMENT '',
  `decisionsD22col` VARCHAR(45) NULL COMMENT '',
  `documentType` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`ada`)  COMMENT '',
  CONSTRAINT `ADA_FK`
    FOREIGN KEY (`ada`)
    REFERENCES `mydb`.`decisions` (`ada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
